### ISSUE TITLE
Mac M1 bug

### ISSUE THREAD

**Issue by TimKieu** [totaljs/hello#1]
On Macbook M1 nodejs 16 (Arm), I can not run: 
hello % node index.js
> DEBUG PID: 90672 (v4)
TypeError: Cannot read property 'hash' of undefined
    at global.HASH (/Users/kevin/dev/github/totaljs/hello/node_modules/total4/utils.js:2679:15)
    at install_build (/Users/kevin/dev/github/totaljs/hello/node_modules/total4/index.js:5871:25)
    at /Users/kevin/dev/github/totaljs/hello/node_modules/total4/index.js:5675:32
    at Array.AP.async (/Users/kevin/dev/github/totaljs/hello/node_modules/total4/utils.js:5111:3)
    at Immediate.async_next (/Users/kevin/dev/github/totaljs/hello/node_modules/total4/utils.js:5119:7)
    at processImmediate (node:internal/timers:466:21)
======= 2021-10-14 15:00:44: TypeError: Cannot read property 'hash' of undefined TypeError: Cannot read property 'hash' of undefined
    at global.HASH (/Users/kevin/dev/github/totaljs/hello/node_modules/total4/utils.js:2679:15)
    at install_build (/Users/kevin/dev/github/totaljs/hello/node_modules/total4/index.js:5871:25)
    at /Users/kevin/dev/github/totaljs/hello/node_modules/total4/index.js:5675:32
    at Array.AP.async (/Users/kevin/dev/github/totaljs/hello/node_modules/total4/utils.js:5111:3)
    at Immediate.async_next (/Users/kevin/dev/github/totaljs/hello/node_modules/total4/utils.js:5119:7)
    at processImmediate (node:internal/timers:466:21)

**Comment by petersirka** [comment]
Sorry guys, I created a critical bug last week with builds. Now it's solved, please reinstall Total.js framework `$ npm install total4@beta`.
